### ISSUE TITLE
parallel download support

### ISSUE THREAD

**Issue by lmeyerov** [fsspec/adlfs#268]
In benchmarks, we're finding significant speedups by using parallel downloads for MB+ individual blobs:

for a 200MB file on an az server <> az store, warm:

- fs.download: 4.9s
- file.write(await (await bc.download_blob()).readall())): 4.3s
- file.write(await (await bc.download_blob(max_concurrency=16)).readall())): 1.3s
- trickier: I think it's even bigger in practice b/c above was a warm read. cold read baselines were more 10-20s.

This is on a node with 8 cores and 2 NICs, and I think < 1 Gbps

Ideally:
- smart default: concurrency defaults to # cores x2 or x4, something like that
- unclear: handling of recursive case
- allow manual overrides
- works with dask, e.g., dd.read_parquet(...)

**Comment by hayesgb** [comment]
@lmeyerov -- Really appreciate this benchmarking!  I've put together a crack at this.  It's currently implemented in the `concurrent_io` branch for:

```
fs.get_file()
fs.put_file()
fs.open()
AzureBlobFile.write()
```

When I timed this on my local machine, `put_file` gave me over 50% reduction in write times, so I'd appreciate any feedback you have.
