### ISSUE TITLE
fsspec 2022.1.0?

### ISSUE THREAD

**Issue by lmeyerov** [fsspec/adlfs#293]
- Any plans to update? We're aligned w/ the rapids/dask ecosystems, and looks like adlfs is pinned on 2021
- To lower the need in the future, maybe switch away from == ?

**Comment by hayesgb** [comment]
Yes, plan to do an update this week.  I've been tied up with changes at work.

What dependency is causing an issue with being pinned?

**Comment by lmeyerov** [comment]
Maybe my python-foo isn't enough

https://github.com/fsspec/adlfs/blob/39d40b3e7b33dfd3719f5ae62cca06c823d343a5/setup.py#L36

seems to conflict with `2022.1.0`... but I'd think that'd work

Ending up ripping out the dep so hard to repro now, apologies =/

**Comment by hayesgb** [comment]
Sorry for the delay in responding.  No worries though.

Just pushed 2022.02.0.
