### ISSUE TITLE
Entrypoint support for abfss prevent this protocol to be overwritten by another package

### ISSUE THREAD

**Issue by pierre-godard** [fsspec/adlfs#302]
Hi!

First of all, I'm not sure if this issue really fits here or if it should be opened in the fsspec main repository as I'm not sure of the best way to solve this (if it should actually be solved).

# Context

I'm building a python package that is defining two protocols via the `fsspec.specs` entrypoint: `adl` and `abfss`.
This package itself depends on adlfs and simply consists in supercharging the `AzureDatalakeFileSystem` and `AzureBlobFileSystem` with default values for the tenant_id, client_id, client_secret, account_name and store_name to fit in our organization.

# Problem

When I'm installing my package in a new python environment, the `adl` protocol defined by default in fsspec is correctly overriden. However, the `abfss` protocol (defined both in my package's entrypoints and in adlfs entrypoints) points to the adlfs' `AzureBlobFileSystem` instead.

# Expected behaviour

I would like my definition of the `abfss` protocol to override the one defined in adlfs.

# Analyzing the issue

In the `fsspec.specs` entrypoints, both the implementations are defined with adlfs implementation coming last.

```python
from importlib.metadata import entry_points
from pprint import pprint
specs = entry_points().get("fsspec.specs", {})
pprint(specs)
```

```
(EntryPoint(name='abfss', value='mypackage:MyAzureBlobFileSystem', group='fsspec.specs'),
 EntryPoint(name='adl', value='mypackage:MyAzureDatalakeFileSystem', group='fsspec.specs'),
 EntryPoint(name='abfss', value='adlfs.AzureBlobFileSystem', group='fsspec.specs'))
```

Having a look at the fsspec `process_entries` function ([link](https://github.com/fsspec/filesystem_spec/blob/0fe49f546a1a1295cba84decf0be4c3ef1d75241/fsspec/__init__.py#L47)) show that these specs are handled in order.

The `mypackage` implementation is first registered before being overriden by the adlfs implementation.

# Possible solutions

Personally, I would prefer my implementation to be prioritized. Maybe there is a way to do it, but I don't have enough knowledge regarding the entrypoints mechanics. If you agree and think this is the way to go, here are the possible solutions I can think of:
- Add `abfss` in the fsspec's known implementations
- Change `process_entries` function so that it prioritize the implementation that is the highest in the list

Those two solutions are to be handled from fsspec's side, that's why I'm unsure of where to report this issue.

Thank you!

**Comment by pierre-godard** [comment]
Thank you! I'll close it here.

**Comment by KeerthiYandaOS** [comment]
@martindurant Looks like there is an entry-point for "abfss" in the setup file https://github.com/fsspec/adlfs/blob/2022.7.0/setup.py#L44-L48 which is not allowing the overriding of entry-point for abfss protocol. I wonder why only abfss has the entry point in setup file?

**Comment by KeerthiYandaOS** [comment]
@martindurant Having abfss entry point in [setup.py](https://github.com/fsspec/adlfs/blob/2022.7.0/setup.py#L44-L48) is not allowing for overriding this protocol by other packages (like our scenario of fsspec_wrapper). Can we implement/move this to known_implementations [here](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/registry.py#L87-L211) along with other protocols?

**Comment by martindurant** [comment]
No, it would not make sense to edit known_implementations, as it would prefer your package to this one for all users. Instead, we should implement the config approach.

Note that your package can add itself to fsspec's protocol registry on import, so a simply workaround might be to get users to always import your package before attempting to use fsspec.

**Comment by KeerthiYandaOS** [comment]
`Note that your package can add itself to fsspec's protocol registry on import, so a simply workaround might be to get users to always import your package before attempting to use fsspec.`

@martindurant Can you please elaborate on the workaround? Currently, we have an entry-points in our fsspec_wrapper repo setup.py for abfss but when I run Pandas commands, the request is reaching the AzureBlobFileSystem instead of the wrapper class.

**Comment by martindurant** [comment]
Lines like the following could appear in your package's init module:
```
import fsspec
fsspec.registrer_implementation("protocol", MyClass)
```

**Comment by KeerthiYandaOS** [comment]
@martindurant Adding below in "_ _init_ _.py" in the fsspec_wrapper package folder, didn't help, the request is still reaching the AzureBlobFileSystem class. Do you have any other workaround or thoughts for overriding the entry points for abfss?
```
from fsspec.registry import register_implementation
register_implementation('abfss', OurPackageClass)
```

**Comment by martindurant** [comment]
Be sure to import your package first. The following demonstrates this working:
```
In [1]: import fsspec

In [2]: class Thrum:
   ...:     pass
   ...:

In [3]: fsspec.register_implementation("file", Thrum)

In [4]: fsspec.filesystem("file")  # overridden entry in known_implementations
Out[4]: <__main__.Thrum at 0x7ff7182f6280>

In [5]: fsspec.filesystem("abfss")
[ValueError from adlfs due to no account name]

In [6]: fsspec.register_implementation("abfss", Thrum)

In [7]: fsspec.filesystem("abfss")  # overridden entrypoint
Out[7]: <__main__.Thrum at 0x7ff71bcb2070>
```

**Comment by KeerthiYandaOS** [comment]
@martindurant This is a kind of an issue here, we can't ask users to import fsspec_wrapper just to run the __init__.py file. 
Users will be importing the Pandas module, inorder to use read_xx or to_xx APIs. Not sure about adding "register_implementation" in Pandas.__init__ file in order to override "abfss" protocol as the issue is in the adlfs setup file.

**Comment by martindurant** [comment]
Unfortunately, in lieu of a config option in fsspec to choose a preferred implementation per protocol, fsspec must pick which implementation best meets users' expectations for a given protocol. At the moment, for "abffs", this is provided by adlfs.

So, certainly change anything on your system to force fsspec to pick the right implementation for you. In the longer term, the config thing is probably the right answer; and these config values can be set in a file or in environment variables.

**Comment by KeerthiYandaOS** [comment]
@martindurant I used Pandas init to register the abfss implementation as it will be the only package installed by the users. But this is still causing issues as we will lose the registration if users reinstall the Pandas package. Can you please suggest if there is any alternate or can we change the entry-point to configuration settings?

**Comment by martindurant** [comment]
fsspec does have a simple config system, for providing default arguments to the various backends. I think it would be reasonable for that system to allow preferring some implementations for a given protocol over others. It just needs to be coded...

I don't know of any way in which we can configure how entrypoints itself finds entries.

**Comment by KeerthiYandaOS** [comment]
Created a pull request in fsspec to avoid the entry-point overriding: https://github.com/fsspec/filesystem_spec/pull/1389
