### ISSUE TITLE
`python_requires` in release `2022.4.0` do not allow to use it in Python 3.8

### ISSUE THREAD

**Issue by gabrielmbmb** [fsspec/adlfs#317]
In the release `2022.2.0` the minimum Python version that you needed to use `adlfs` was Python 3.7 (`python_requires` was `>3.6`). The latest release, `2022.4.0` does not allow to install `adlfs` when using Python 3.8 because the `python_requires` condition in `setup.py` is set to `>3.8`, but in the `classifiers` the package has `"Programming Language :: Python :: 3.8"` Is this intented? Shouldn't it be `>=3.8`?

**Comment by matt-erhart** [comment]
```bash
Using version ^2022.4.0 for adlfs

Updating dependencies
Resolving dependencies...

  SolverProblemError

  The current project's Python requirement (>=3.8,<4.0) is not compatible with some of the required packages Python requirement:
    - adlfs requires Python >3.8, so it will not be satisfied for Python 3.8

  Because adlfs (2022.4.0) requires Python >3.8
   and no versions of adlfs match >2022.4.0,<2023.0.0, adlfs is forbidden.
```

I actually can't install it with 3.8.8 or 3.9. I get the same error above.

**Comment by matt-erhart** [comment]
I was able to install adlfs==2022.2.0 on python 3.9.

**Comment by TomAugspurger** [comment]
Yeah, this looks like a bug. @hayesgb I think it'd be best to update https://github.com/fsspec/adlfs/blob/37324d0e952fd2f5f7b382f453fbcac99e2fb130/setup.py#L28 to `>=3.8.0` and then cutting a new release.

We could yank the 2022.4.0 release, but that's probably not worth the hassle.
