### ISSUE TITLE
aiohttp not in requirements

### ISSUE THREAD

**Issue by benrutter** [fsspec/adlfs#343]
Looks like the latest version removes aiohttp from requirements, but not imports, meaning that an error will be raised importing adlfs if aiohttp isn't additionally installed.

Reproduction steps:

1. Create a fresh python environment
2. Install the latest version of adlfs
3. Import adlfs

This should throw a module not found error for aiohttp.

I think the resolution for this is just to add aiohttp into the requirements? I've put in a pull request if that is the case here: https://github.com/fsspec/adlfs/pull/344

**Comment by TomAugspurger** [comment]
This is fixed and released to PyPI as 2022.9.1: https://pypi.org/project/adlfs/2022.9.1/
