### ISSUE TITLE
`close_credential` fails when using string token

### ISSUE THREAD

**Issue by willbowditch** [fsspec/adlfs#346]
I'm using `adlfs` to download some files:

```py
from fsspec.core import url_to_fs

azure_filesystem, azure_path = url_to_fs(
    'abfs://footprints/global/2022-07-06/ml-buildings.parquet/RegionName=United Kingdom',
    account_name='bingmlbuildings',
    credential='string_credential'
)
azure_filesystem.get(
    'abfs://footprints/global/2022-07-06/ml-buildings.parquet/RegionName=United Kingdom',
    '/local/path',
    recurisve=True,
)
```

Where `string_credential` is an access token generated by another Azure library ([planetary-computer](https://pypi.org/project/planetary-computer/)) for temporary access to that file. 

At the end of the application running, it raises an error when attempting to `close_credentials`

```stdout
Traceback (most recent call last):
  File "/Users/wb/.pyenv/versions/3.9.13/lib/python3.9/weakref.py", line 667, in _exitfunc
    f()
  File "/Users/wb/.pyenv/versions/3.9.13/lib/python3.9/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/Users/wb/projects/assets/workflows/ms-buildings-ingest/.venv/lib/python3.9/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/Users/wb/projects/assets/workflows/ms-buildings-ingest/.venv/lib/python3.9/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/Users/wb/projects/assets/workflows/ms-buildings-ingest/.venv/lib/python3.9/site-packages/adlfs/utils.py", line 74, in close_credential
    await file_obj.credential.close()
AttributeError: 'str' object has no attribute 'close'
```

Is this a bug? I'm not familiar with async python, but unless that introduces `.close()` I'm wondering if the fix would be to add a condition along the lines of:

```py
async def close_credential(file_obj):
    """
    Implements asynchronous closure of credentials for
    AzureBlobFile objects
    """
    if file_obj.credential is not None and not isinstance(file_obj.credential, str):
        await file_obj.credential.close()
```

Thanks

**Comment by hayesgb** [comment]
@willbowditch -- Just confirming.  The planetary-computer [docs](https://planetarycomputer.microsoft.com/docs/concepts/sas/) suggest they call for sas-token, which is an exposed authentication parameter by adlfs, as shown here:  https://github.com/fsspec/adlfs/blob/591485b9d77448cd6e791b49bda8942ef03507bf/adlfs/spec.py#L341.

Is there a different authentication method?

**Comment by willbowditch** [comment]
Thanks @hayesgb - you're right, swapping using `sas_token` resolves it. 

The example from the planetry-computer docs I was following suggests you can do this:

```python
    signed_handle = planetary_computer.sign(data_handle)

    azure_filesystem, azure_path = url_to_fs(
        signed_handle.href,
        **signed_handle.extra_fields["table:storage_options"],
    )
```

Where the `signed_handle.extra_fields["table:storage_options"]` contains `account_name` and `credential`.

Renaming credential as `sas_token` resolves it, e.g.:

```python
    signed_handle = planetary_computer.sign(data_handle)

    signed_handle.extra_fields["table:storage_options"][
        "sas_token"
    ] = signed_handle.extra_fields["table:storage_options"].pop("credential")

    azure_filesystem, azure_path = url_to_fs(
        signed_handle.href,
        **signed_handle.extra_fields["table:storage_options"],
    )
```

**Comment by TomAugspurger** [comment]
Is there a reason adlfs doesn't match azure-storage-blob's behavior when the user provides a `credential=<sas-token>` to `ContainerClient`? IIUC using `credential=<sas-token>` will modify the endpoint to include the SAS token in the URL.

And I think the AzureBlobFileSystem docs currently say

```
    credential: TokenCredential or SAS token
        The credentials with which to authenticate.  Optional if the account URL already has a SAS token.
        Can include an instance of TokenCredential class from azure.identity
```

so something will need to be updated. IMO passing `credential=token` is fine, but we need to update cleanup code.
