### ISSUE TITLE
Container exists / Permissions issue

### ISSUE THREAD

**Issue by aersam** [fsspec/adlfs#384]
Hi there

I have a sas_token that somehow does not allow asking for the container properties, only for folders inside. This breaks adlfs's _mkdir which is called by a third-party lib I don't control (pyarrow). Is there some way to not ignore the error on _container_exists if a sas_token was provided?

**Comment by aersam** [comment]
Monkey patching works as a workaround:

```python

async def _noop_container_exists(self = None, container_name = None):
        return True 

fs, path = fsspec.core.url_to_fs(url, **storage_options)
if "_container_exists" in dir(fs):
    # monkey patch adfs because of missing permissions 
    fs._container_exists = _noop_container_exists # https://github.com/fsspec/adlfs/issues/384

```

**Comment by TomAugspurger** [comment]
Yeah, this is pretty unfortunate. Even if you're using Azure AD RBAC for auth, you might only have permission within the container.

FWIW, `azcopy` will print out a warning in some cases like this.

I would propose two things:

1. Place the main part of `mkdir` in a `try / except` block. If we do get a permission error,  we emit a warning explaining that we couldn't create the storage container, but things may work if the container already exists
2. A new parameter in `AzureBlobFileSystem` that controls whether that warning is emitted. By default we should warn. I suppose this could be a 3-way switch: warn / ignore / raise an error.
