### ISSUE TITLE
ls does not work with protocol prefix

### ISSUE THREAD

**Issue by JoostvDoorn** [fsspec/adlfs#395]
Many commands seem to work with a protocol prefix as they call `_strip_protocol` internally however ls doesn't seem to work for ls. It seems consistent with s3fs and gcsfs that this is supported as well by adlfs.

**Comment by mivade** [comment]
I ran into the same issue. If I try to do

```python
fs.listdir("az://my-container/path")
```

I get an empty list. If instead I do

```python
fs.listdir("my-container/path")
```
I get all the blobs in `path`. Every other command I've tried works fine with the protocol in place so this took a bit of exploration to figure out.
