### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by daavoo** [fsspec/adlfs#412]
Hi there! 

I just wanted to know if there is something blocking a new release and what is the process / who is in charge of releasing it?

The last one was [`2023.1.0`](https://github.com/fsspec/adlfs/releases/tag/2023.1.0) and several bugfixes were merged since: https://github.com/fsspec/adlfs/compare/2023.1.0...main

**Comment by efiop** [comment]
Pushed 2023.4.0
