### ISSUE TITLE
UserWarning: Failed to fetch container properties for CONTAINER_NAME. Assume it exists already

### ISSUE THREAD

**Issue by fdcastel** [fsspec/adlfs#423]
Using `adlfs` with `Pandas`, and a simple `to_parquet` call:

```python
data.to_parquet(
    path="abfss://CONTAINER@ACCOUNT.dfs.core.windows.net/FOLDER",
    partition_cols=["ONE_COLUMN"],
    existing_data_behavior="delete_matching",
)
```

This works fine. But I always get this warning

```
.venv\lib\site-packages\adlfs\spec.py:1132: UserWarning: Failed to fetch container properties for CONTAINER.
Assume it exists already
```

which is very annoying since it keeps spamming all my logs. 

What I must do to clear this warning? Am I missing a permission of something?

Using: 
- Python: `3.10.11`
- Pandas: `2.1.0`
- adlfs: `2023.8.0`

**Comment by TomAugspurger** [comment]
You want `assume_container_exists=True`. I think you pass that through pandas' `to_parquet` with `storage_options`
