### ISSUE TITLE
Avoid private APIs from azure.storage

### ISSUE THREAD

**Issue by TomAugspurger** [fsspec/adlfs#426]
- [ ] https://github.com/fsspec/adlfs/blob/4b704b1a5f39ec2350a8be44d9cb117aee9b1719/adlfs/spec.py#L25
- [ ] https://github.com/fsspec/adlfs/blob/4b704b1a5f39ec2350a8be44d9cb117aee9b1719/adlfs/spec.py#L26
- [ ] https://github.com/fsspec/adlfs/blob/4b704b1a5f39ec2350a8be44d9cb117aee9b1719/adlfs/spec.py#L28

**Comment by jalauzon-msft** [comment]
Just to help out a little, `BlobBlock`, `BlobProperties`, `BlobType`, and `BlobPrefix` are all exported from the main SDK so should all be able to be imported directly from `azure-storage-blob`.

`create_configuration` is not exported and is not really recommended to be used, especially just to get the default block size. Unfortunately, we (the SDK team) don't really have an export for our default block size at this moment, but it is 4 MiB (4 * 1024 * 1024) and not likely to change anytime soon so you could consider just hardcoding it. If you really think you want that constant exported, feel free to open an issue to the SDK and we can consider adding it (but may ultimately decide not to).

**Comment by benrutter** [comment]
create_configuration probably needs a bit of discussion, but I'd be down to put in a PR for this to help get it fixed. It should just be a drop in replacement on the imports and then a quick check that no tests are broken.
