### ISSUE TITLE
Can I use a bearer token / entra ID token for authentication?

### ISSUE THREAD

**Issue by keen85** [fsspec/adlfs#465]
Is there a way to use a bearer token instead of `credential` object for authentication when using `AzureBlobFileSystem`/`AzureDatalakeFile`?

**Comment by TomAugspurger** [comment]
adlfs uses `azure-storage-blob` internally. Its list of supported methods are at https://learn.microsoft.com/en-us/python/api/overview/azure/storage-blob-readme?view=azure-python#types-of-credentials.

I'm not sure, but I don't think that a bearer token is valid. I think it needs to be a `TokenCredential` instance (like `DefaultAzureCredential`), a SAS token, or an Account Key.

If you really need to pass a string as a credential, you might be able to create a [User Delegation SAS](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas)
