### ISSUE TITLE
object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by dmkusner** [fsspec/adlfs#470]
Whenever I try to use adlfs version 2024.4.1 (only version I've ever used) my code works but on exit/cleanup it generates the following stack trace:

Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 667, in _exitfunc
    f()
  File "/usr/lib/python3.10/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/david_kusner/dmk_python/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/david_kusner/dmk_python/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/david_kusner/dmk_python/lib/python3.10/site-packages/adlfs/utils.py", line 78, in close_credential
    await file_obj.credential.close()
TypeError: object NoneType can't be used in 'await' expression

Here is some sample code that exhibits this issue. It also happens if I acquire an AzureBlobFileSystem and work with that. Note that code works -- I can read the file and print out its contents. The stack trace occurs immediately afterwards. I haven't found any way to supress it. I'm not using any async here, so not sure why an 'await' is involved.

import fsspec
from azure.identity import AzureCliCredential
from adlfs import AzureBlobFileSystem

creds = AzureCliCredential()
storage_options = {"credential": creds}

adlFile = "abfss://CONTAINER@ACCOUNT.dfs.core.windows.net/work/dkusner/foo.txt"

with fsspec.open(adlFile, **storage_options) as f:
    print(f.read())

**Comment by dmkusner** [comment]
Saw a suggestion to use azure.internal.aio library in issue #431, which I did with success. Stack trace no longer happens with async AzureCliCredential.

**Comment by mhtrinh** [comment]
I am no expert to async, but when removing the `await` here:
https://github.com/fsspec/adlfs/blob/5c24b2e886fc8e068a313819ce3db9b7077c27e3/adlfs/utils.py#L78

it solved the issue ...

**Comment by TomAugspurger** [comment]
Closing in favor of https://github.com/fsspec/adlfs/issues/431.
